#!/usr/bin/env bash
# Display information about subdomains

# Display usage message if no domain is provided
if [ -z "$1" ]; then
  echo "Usage: $0 <domain> [subdomain]"
  exit 1
fi

domain="$1"
subdomain="$2"

# Function to query DNS records
get_record() {
  record_type="$1"
  subdomain="${2:-$domain}"
  dig "$subdomain.$domain" +short -t "$record_type"
}

# Display information about specific subdomain
if [ -n "$subdomain" ]; then
  record_type="$(get_record A)"
  destination="$(get_record A)"
  if [ -z "$record_type" ]; then
    echo "Subdomain $subdomain does not exist."
  else
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
  fi
else
  # Display information about specific subdomains
  for subdomain in www lb-01 web-01 web-02; do
    record_type="$(get_record A "$subdomain")"
    destination="$(get_record A "$subdomain")"
    if [ -z "$record_type" ]; then
      echo "Subdomain $subdomain does not exist."
    else
      echo "The subdomain $subdomain is a $record_type record and points to $destination"
    fi
  done
fi
