#!/usr/bin/env bash
# Display information about subdomains

# Usage: ./0-world_wide_web.sh <domain> [<subdomain>]

domain="$1"
subdomain="$2"

# Check if the required arguments are provided
if [ -z "$domain" ]; then
  echo "Error: Please provide a domain name as the first argument."
  exit 1
fi

# Define the subdomains to check if no subdomain is provided
if [ -z "$subdomain" ]; then
  subdomains=(www lb-01 web-01 web-02)
else
  subdomains=("$subdomain")
fi

# Check the DNS record for each subdomain
for subdomain in "${subdomains[@]}"; do
  record_type=$(dig "$subdomain.$domain" +short | awk -F '[: ]+' '{print $2}')
  destination=$(dig "$subdomain.$domain" +short | awk -F '[: ]+' '{print $5}')

  if [ -z "$record_type" ]; then
    echo "Error: Subdomain '$subdomain' doesn't exist for domain '$domain'."
  else
    echo "The subdomain '$subdomain' is a '$record_type' record and points to '$destination'."
  fi
done
