#!/usr/bin/env bash
# COnfigure a redirect in nginx

# Update the package list
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Ensure nginx is running
sudo service nginx start

# Configure redirection in Nginx
echo "server {
        listen 80;
        listen [::]:80;

        server_name cank.tech;

        root /var/www/html;
        index index.html;

        location / {
            try_files \$uri \$uri/ =404;
        }
        
        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Verify nginx configuration
sudo nginx -t

# Reload nginx configuration
sudo service nginx reload
