#!/usr/bin/env bash

# Execute the script for installing Nginx
./1-install_nginx_web_server.sh

# Configure redirection in Nginx
sudo sed -i '/listen 80;/a \\n\tlocation /redirect_me {\n\t\treturn 301 http://www.redirectedpage.com;\n\t}' /etc/nginx/sites-available/default

# Verify nginx configuration
sudo nginx -t

# Reload nginx configuration
sudo service nginx reload
