#!/usr/bin/env bash

# Update the package list
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Ensure nginx is running
sudo service nginx start

# Configure redirection in Nginx
sudo sed -i -e '/listen 80;/a \\n\tlocation /redirect_me {\n\t\treturn 301 http://www.redirectedpage.com;\n\t}' -e 's/^\(listen 80;\)/\1/' /etc/nginx/sites-available/default

# Verify nginx configuration
sudo nginx -t

# Reload nginx configuration
sudo service nginx reload
