#!/usr/bin/env bash
# Configure a redirect and error handling in nginx

# Update the package list
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Ensure nginx is running
sudo service nginx start

# Configure redirection and error handling in Nginx
echo "server {
        listen 80;
        listen [::]:80;

        server_name cank.tech;

        root /var/www/html;
        index index.html;

        location / {
            try_files \$uri \$uri/ =404;
        }
        
        location /redirect_me {
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        error_page 404 /404.html;
        location = /404.html {
            root /var/www/html;
            internal;
            return 404 \"Ceci n'est pas une page\";
        }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart nginx without using systemctl
sudo service nginx restart

# Verify nginx configuration
sudo nginx -t

# Reload nginx configuration
sudo service nginx reload
