#!/usr/bin/env bash

# Execute the script for installing Nginx and configuring redirection
./3-redirection.sh

# Configure custom 404 page in Nginx
sudo sed -i '/server_name _;/a \\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t\treturn 404 "Ceci n'\''est pas une page";\n\t}' /etc/nginx/sites-available/default

# Verify nginx configuration
sudo nginx -t

# Reload nginx configuration
sudo service nginx reload
