#!/usr/bin/env bash
# This script configures Nginx to add a custom HTTP header to its response.

# Update package list and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Configure custom HTTP header
sudo echo "add_header X-Served-By \$HOSTNAME;" | sudo tee -a /etc/nginx/sites-available/default

# Restart Nginx for changes to take effect
sudo service nginx restart
