#!/usr/bin/env bash
# This script installs and configures HAproxy on lb-01.

# Update package list
sudo apt-get update

# Install HAproxy
sudo apt-get -y install haproxy

# Configure HAproxy
sudo sed -i 's/.*frontend.*$/frontend main\n\tbind \*:80\n\tdefault_backend webservers/' /etc/haproxy/haproxy.cfg
sudo echo -e "backend webservers\n\tbalance roundrobin\n\tserver web-01 3.90.82.131:80 check\n\tserver web-02 34.202.159.65:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAproxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAproxy for changes to take effect
sudo service haproxy restart
