#!/usr/bin/env bash
# A bash script to ping an address

# Check if an argument is provided
if [ $# -ne 1 ]; then
    script_name=$(basename "$0")
    echo "Usage: $script_name {IP_ADDRESS}"
    exit 1
fi

# Ping the IP address 5 times and display the result
ping -c 5 "$1"
