#!/usr/bin/env bash
# Bash script that configures Nginx to listen on port 80

# Replace 'listen 80 default_server;' with 'listen 80;' in the Nginx configuration
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart the Nginx service
service nginx restart;
