#!/bin/bash

# Define the file name
file_name="school"

# Check if the file exists
if [ -e "$file_name" ]; then
    echo "school file exists"

    # Check if the file is empty
    if [ -s "$file_name" ]; then
        echo "school file is not empty"

        # Check if the file is a regular file
        if [ -f "$file_name" ]; then
            echo "school is a regular file"
        else
            # The file is not a regular file
            :
        fi
    else
        echo "school file is empty"
    fi
else
    echo "school file does not exist"
fi
