#!/usr/bin/env bash
# A bash script that displays all active IPv4 IPs on the machine it’s executed on.

# Use ifconfig to get network interface information and grep for IPv4 addresses
ifconfig | grep -oE 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1' | awk '{print $2}'
