#!/usr/bin/env bash
# Configures Nginx to run as nginx user and listen on port 8080 in 7 lines or less

sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
service nginx restart
