#!/usr/bin/env bash
# Bash script to connect to my server
# using the generated private key

# Set the server's hostname or IP address
server="18.207.3.75"

# Use ssh with single-character flags to connect
# with the private key ~/.ssh/school and the user ubuntu
ssh -i ~/.ssh/school ubuntu@$server