#!/usr/bin/env bash
# Bash script to create an RSA key pair

# Set the key file names
private_key="school"
public_key="${private_key}.pub"

# Set the number of bits for the key
key_bits=4096

# Set the passphrase
passphrase="betty"

# Create the RSA key pair
ssh-keygen -t rsa -b $key_bits -f $private_key -N $passphrase
